export const MAPA_SINTOMAS = {
  febre: 'Febre',
  calafrios: 'Calafrios',
  fadiga: 'Fadiga',
  mal_estar: 'Mal-estar geral',
  dor_cabeca: 'Dor de cabeça',
  tontura: 'Tontura',
  convulsao: 'Convulsão',
  deficit_motor: 'Déficit motor súbito',
  confusao_mental: 'Confusão mental',
  alteracao_consciencia: 'Alteração do nível de consciência',
  tosse: 'Tosse',
  falta_ar: 'Falta de ar',
  dor_garganta: 'Dor de garganta',
  chiado_peito: 'Chiado no peito',
  escarro: 'Produção de escarro',
  apneia: 'Apneia',
  nausea: 'Náusea',
  vomitos: 'Vômitos',
  diarreia: 'Diarreia',
  dor_abdominal: 'Dor abdominal',
  sangue_fezes: 'Sangue nas fezes',
  constipacao: 'Constipação',
  distensao_abdominal: 'Distensão abdominal',
  dor_muscular: 'Dor muscular',
  dor_articulacoes: 'Dor nas articulações',
  perda_olfato: 'Perda de olfato',
  perda_paladar: 'Perda de paladar',
  erupcao_cutanea: 'Erupção cutânea',
  coceira: 'Coceira',
  dor_toracica: 'Dor torácica',
  palpitacoes: 'Palpitações',
  edema_mmii: 'Edema de membros inferiores',
  pressao_alta: 'Pressão alta',
  disuria: 'Dor ao urinar',
  hematúria: 'Urina com sangue',
  retencao_urinaria: 'Retenção urinária',
  sangramento_vaginal: 'Sangramento vaginal',
  dor_pelvica: 'Dor pélvica',
  atraso_menstrual: 'Atraso menstrual',
  fratura_exposta: 'Fratura exposta',
  entorse: 'Entorse',
  ferimento_sangramento: 'Ferimento com sangramento',
  hipoglicemia: 'Hipoglicemia',
  hiperglicemia: 'Hiperglicemia',
  sudorese: 'Sudorese excessiva',
  choro_inconsolavel: 'Choro inconsolável',
  letargia: 'Letargia',
  irritabilidade: 'Irritabilidade'
}

export const CATEGORIAS_SINTOMAS = {
  Geral: '🌡️ Geral',
  Neurológico: '🧠 Neurológico',
  Respiratório: '🫁 Respiratório',
  Gastrointestinal: '🧻 Gastrointestinal',
  Muscular: '💪 Muscular',
  Sensorial: '👁️👂 Sensorial',
  Dermatológico: '🧴 Dermatológico',
  Cardiovascular: '❤️ Cardiovascular',
  Geniturinário: '🚽 Geniturinário',
  Ginecológico: '🌸 Ginecológico',
  Trauma: '🩹 Trauma',
  Endocrinológico: '🦋 Endocrinológico',
  Pediátrico: '🧸 Pediátrico'
}